version: '3.2'
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5435:5432'
    environment:
      - POSTGRESQL_USERNAME=team
      - POSTGRESQL_PASSWORD=team
      - POSTGRESQL_DATABASE=team
